### ISSUE TITLE
Portfolio optimizer upload csv raises exception

### ISSUE THREAD

**Issue by jordansamuels** [pyviz-topics/examples#76]
I'm running the portfolio optimizer off of the files downloaded from https://examples.pyviz.org/assets/portfolio_optimizer.zip .  Everything appears to work fine, except when I upload a csv of stock prices, I get the stack trace below.  This does not happen when I use https://portfolio-optimizer.pyviz.demo.anaconda.com/portfolio, which works fine with the same csv file.  I also get the same error when I run from source (abc016730c8ccf04a0a2fef35f4232e3f2ec9468).  

I'm using 
```
% conda --version; anaconda-project --version
conda 4.7.12
0.8.3
```
on OSX.  

Exception trace:
```
2019-11-25 09:42:26,235 Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7fd1e0572a58>>, <Future finished exception=RuntimeError('FileInput.filename is a readonly property',)>)
Traceback (most recent call last):
  File "/private/tmp/portfolio_optimizer/envs/default/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/private/tmp/portfolio_optimizer/envs/default/lib/python3.6/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/private/tmp/portfolio_optimizer/envs/default/lib/python3.6/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/private/tmp/portfolio_optimizer/envs/default/lib/python3.6/site-packages/bokeh/server/session.py", line 70, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/private/tmp/portfolio_optimizer/envs/default/lib/python3.6/site-packages/bokeh/server/session.py", line 191, in with_document_locked
    return func(*args, **kwargs)
  File "/private/tmp/portfolio_optimizer/envs/default/lib/python3.6/site-packages/bokeh/document/document.py", line 1127, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "/private/tmp/portfolio_optimizer/envs/default/lib/python3.6/site-packages/bokeh/document/document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "/private/tmp/portfolio_optimizer/envs/default/lib/python3.6/site-packages/bokeh/document/document.py", line 1126, in invoke
    return f(*args, **kwargs)
  File "/private/tmp/portfolio_optimizer/envs/default/lib/python3.6/site-packages/bokeh/document/document.py", line 916, in remove_then_invoke
    return callback(*args, **kwargs)
  File "/private/tmp/portfolio_optimizer/envs/default/lib/python3.6/site-packages/panel/viewable.py", line 653, in _change_event
    self.set_param(**self._process_property_change(events))
  File "/private/tmp/portfolio_optimizer/envs/default/lib/python3.6/site-packages/param/parameterized.py", line 1219, in inner
    return fn(*args, **kwargs)
  File "/private/tmp/portfolio_optimizer/envs/default/lib/python3.6/site-packages/param/parameterized.py", line 2573, in set_param
    return self_or_cls.param.set_param(*args,**kwargs)
  File "/private/tmp/portfolio_optimizer/envs/default/lib/python3.6/site-packages/param/parameterized.py", line 1365, in set_param
    self_._batch_call_watchers()
  File "/private/tmp/portfolio_optimizer/envs/default/lib/python3.6/site-packages/param/parameterized.py", line 1480, in _batch_call_watchers
    watcher.fn(*events)
  File "/private/tmp/portfolio_optimizer/envs/default/lib/python3.6/site-packages/panel/viewable.py", line 604, in param_change
    self._update_model(events, msg, root, model, doc, comm)
  File "/private/tmp/portfolio_optimizer/envs/default/lib/python3.6/site-packages/panel/viewable.py", line 584, in _update_model
    model.update(**msg)
  File "/private/tmp/portfolio_optimizer/envs/default/lib/python3.6/site-packages/bokeh/core/has_props.py", line 376, in update
    setattr(self, k, v)
  File "/private/tmp/portfolio_optimizer/envs/default/lib/python3.6/site-packages/bokeh/core/has_props.py", line 280, in __setattr__
    super(HasProps, self).__setattr__(name, value)
  File "/private/tmp/portfolio_optimizer/envs/default/lib/python3.6/site-packages/bokeh/core/property/descriptors.py", line 543, in __set__
    raise RuntimeError("%s.%s is a readonly property" % (obj.__class__.__name__, self.name))
RuntimeError: FileInput.filename is a readonly property
```

**Comment by jordansamuels** [comment]
This also happens on Linux with:
```
% conda --version; anaconda-project --version
conda 4.7.12
0.8.3
```
